### PR TITLE
Example of batch/throttle of large lists of inputs

### PR DESCRIPTION
**Pull request by julien-c**

### CODE REVIEW

**Review by srush — COMMENTED** [review]
Not sure I understand this. Should we just build this into the client so that it works with batches? Or is it model specific how to do chunking?

**Comment by julien-c** [comment]
This is for a customer to the paid version of the Inference API, who is looking to send bulk volumes of sentences (e.g 1,000), in short spikes.

The API works with batches out of the box but obviously not batches of arbitrarily large size :)

We also don't want them to send all requests in parallel, so this is an example of how they can sequentially batch their documents

**Comment by julien-c** [comment]
we don't necessarily have to merge this if it's too localized

**Review by srush — APPROVED** [review]
Oh I see. Sounds good.

**Pull request merged**
